WebCompiler/Models/CompileHistory.cs
namespace WebCompiler.Models;

public partial class CompileHistory
{
    public int Id { get; set; }

    public DateTime CompileDate { get; set; }

    public string? Content { get; set; }

    public string CodeLanguage { get; set; } = null!;

    public string Title { get; set; } = null!;

    public int AccountId { get; set; }

    public virtual Account Account { get; set; } = null!;
}

WebCompiler/Controllers/CompileHistoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using WebCompiler.Models;

namespace WebCompiler.Services
{
    public class CompileHistoryController : Controller
    {

        private readonly WebCompilerContext db;
        public CompileHistoryController(WebCompilerContext context)
        {
            db = context;
        }

        [HttpPost]
        public IActionResult SaveCompileHistory(string content, string title)
        {
            int count = 0;
            ++count;
            string langauge = HttpContext.Session.GetString("language") ?? "";
            int accountId = HttpContext.Session.GetInt32("accountId") ?? 1;

            CompileHistory newHistory = new CompileHistory
            {
                Title = title,
                CompileDate = DateTime.Now,
                Content = content,
                AccountId = accountId,
                CodeLanguage = langauge,
            };

            // Save to database
            db.CompileHistories.Add(newHistory); // Adjust to match your DbSet name
            db.SaveChanges();

            List<CompileHistory> cpList = db.CompileHistories.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CompileDate).ToList();
            return PartialView("~/Views/Shared/_CompileHistory.cshtml", cpList);
        }

        public IActionResult showOldCompile(int compileId)
        {

            CompileHistory? cpHistoryOld = db.CompileHistories.FirstOrDefault(c => c.Id == compileId);
            if (cpHistoryOld == null)
            {
                throw new Exception($"No CompileHistory found with ID {compileId}");
            }
           
            switch (cpHistoryOld.CodeLanguage)
            {
                case "csharp":
                    return RedirectToAction("Csharp", "Compile", new { oldCompileId = compileId });
                case "python":
                    return RedirectToAction("Python", "Compile", new { oldCompileId = compileId });
                case "java":
                    return RedirectToAction("Java", "Compile", new { oldCompileId = compileId });
                case "javascript":
                    return RedirectToAction("Javascript", "Compile", new { oldCompileId = compileId });
                case "cpp":
                    return RedirectToAction("Cpp", "Compile", new { oldCompileId = compileId });
                case "r":
                    return RedirectToAction("R", "Compile", new { oldCompileId = compileId });
                case "golang":
                    return RedirectToAction("Go", "Compile", new { oldCompileId = compileId });
                default:
                    return RedirectToAction("Swift", "Compile", new { oldCompileId = compileId });
            }

        }

        [HttpDelete]
        public IActionResult DeleteOldCompile(int compileId)
        {
            CompileHistory? cpHistory = db.CompileHistories.FirstOrDefault(c => c.Id == compileId);
            int accountId = HttpContext.Session.GetInt32("accountId") ?? 1;
            if (cpHistory == null)
            {
                throw new Exception($"No CompileHistory found with ID {compileId}");
            }
            db.CompileHistories.Remove(cpHistory);
            db.SaveChanges();

            List<CompileHistory> cpList = db.CompileHistories.Where(x => x.AccountId == accountId).OrderByDescending(x => x.CompileDate).ToList();
            return PartialView("~/Views/Shared/_CompileHistory.cshtml", cpList);
        }



    }
}

WebCompiler/Controllers/ShareController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCompiler.Models.DTOs;


namespace WebCompiler.Controllers
{
    public class ShareController : Controller
    {
        private readonly RedisService _redisService;
        private readonly ILogger<ShareController> _logger;

        public ShareController(RedisService redisService, ILogger<ShareController> logger)
        {
            _redisService = redisService;
            _redisService.Connect();
            _logger = logger;

            if (_redisService.IsConnected())
            {
                _logger.LogInformation("Successfully connected to Redis.");
            }
            else
            {
                _logger.LogError("Unable to connect to Redis.");
            }
        }

        [HttpPost]
        public async Task<ActionResult> SaveCode()
        {
            if (!Request.ContentType.Contains("application/json"))
            {
                return BadRequest("Content-Type should be application/json");
            }

            var reader = new StreamReader(Request.Body);
            var jsonData = await reader.ReadToEndAsync();

            if (string.IsNullOrWhiteSpace(jsonData))
            {
                return BadRequest("Empty request body");
            }

            dynamic data = JsonConvert.DeserializeObject(jsonData);
            string content = data?.content;
            string language = data?.lang;

            if (content == null)
            {
                return BadRequest("Invalid JSON format");
            }

            string key = Guid.NewGuid().ToString();
            _redisService.SaveCode(key, content, language);

            string shareUrl = Url.Action("ViewCode", "Share", new { key }, Request.Scheme);
            return Json(new { shareUrl });
        }

        public IActionResult ViewCode(string key)
        {
            var code = _redisService.GetCode(key);
            var language = _redisService.GetLanguage(key);

            if (code == null)
            {
                return NotFound();
            }

            ViewBag.Code = code;
            ViewBag.language = language;

            return View();
        }

    }
}

WebCompiler/ViewComponents/DrawnerViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebCompiler.ViewComponents
{
    public class DrawnerViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebCompiler/ViewComponents/HeadViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace WebCompiler.ViewComponents
{
    public class HeadViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebCompiler/ViewComponents/ScriptViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace WebCompiler.ViewComponents
{
    public class ScriptViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebCompiler/ViewComponents/SideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebCompiler.Models;

namespace WebCompiler.ViewComponents
{
    public class SideBarViewComponent : ViewComponent
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly WebCompilerContext _db;

        public SideBarViewComponent(IHttpContextAccessor httpContextAccessor, WebCompilerContext db)
        {
            _httpContextAccessor = httpContextAccessor;
            _db = db;
        }

        public IViewComponentResult Invoke()
        {
            HttpContext.Session.SetInt32("accountId", 1);
            int accountId = HttpContext.Session.GetInt32("accountId") ?? 0;

            if (accountId == 0)
            {
                return View("_SideBar");
            }
            else
            {
                List<CompileHistory> cpHistory = _db.CompileHistories
                    .Where(c => c.AccountId == accountId)
                    .OrderByDescending(x=>x.CompileDate)
                    .ToList();

                return View("CompileHistory", cpHistory);
            }
        }
    }
}

WebCompiler/Views/Shared/Python.cshtml
<!DOCTYPE html>
<html>

<head>
    @await Component.InvokeAsync("Head")
</head>

<body>
    <!-- <select id="language-changer"></select> -->
    <div class="container" id="root" data-lang="python">
        <div class="spinner">
            <div class="loader"><span>{</span><span>}</span></div>
        </div>
        @await Component.InvokeAsync("Drawner")
        <!-- Share code -->
        <!-- Progress bar: share link generating modal -->
        <div class="share-link-generating-modal" style="display: none;">
            <div class="modal-backdrop-share">
            </div>

            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Generating Link</h2>
                    <h2 class="modal-title modal-title-mob">Generating Link</h2>
                </div>
                <div class="modal-body">
                    <div class="progress-bar">
                        <div class="progress"></div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Notification -->
        <div class="notification " id="notification" style="display:none;">
            <div class="check-icon-wrapper">
                <img src="https://cdn.playground-v2.programiz.com/assets/icons/check.svg" alt="check">
            </div>

            <div class="notification-message-wrapper">
                <p class="notification-message"></p>
                <button type="button" class="close-modal-notification" title="Close">
                    <img class="svg" src="https://cdn.playground-v2.programiz.com/assets/icons/close-v2-small.svg" />
                </button>
            </div>
        </div>

        <!-- Share link modal -->
        @await Component.InvokeAsync("ShareLink")

        <!-- Share code end -->

        <div class="wrapper">
            <div class="header">
                <div class="header-wrapper">
                    <div class="burger-menu">
                        <button type="button" class="burger-menu-btn" title="Open navigation">
                            <img class="svg burger-menu-btn-icon" src="https://cdn.playground-v2.programiz.com/assets/icons/burger.svg" />
                        </button>
                    </div>
                    <div class="logo-wrapper">
                        <h1 class="logo-title-wrapper">
                            <a href="https://www.programiz.com/" target="_blank" class="logo-link">
                                <img id="logo" src="https://cdn.playground-v2.programiz.com/assets/logos/logo.svg" />
                                <span class="logo-sub-title-wrapper">
                                    <span class="logo-sub-title">
                                        Python                    Online Compiler
                                    </span>
                                </span>
                            </a>
                        </h1>
                    </div>
                </div>
                <div class="compiler-header-ad">
                    <div id="div-gpt-ad-Programizcom36786" class="content-top-ad">
                    </div>

                    <!-- buysell ads -->
                    <div class="compiler-header-ad" id="carbon-block"></div>

                </div>
                <div id="add-replacement"></div>

                <div id="feedback-mobile">
                    <a id="mobile-ad-link">&nbsp;Learn Python</a>
                </div>
            </div>
            <div class="mobile-top-bar clearfix">
                <div class="pills-wrapper">
                    <div class="pills clearfix">
                        <button class="pill active compiler-pill">
                            main.py
                        </button>
                        <button class="pill shell-pill">
                            Output
                        </button>
                    </div>
                </div>

                <!-- Change the position of option wrapper which contain dark mode toggle and share in mob view -->
                <div class="options-wrapper">
                    <!-- <div id="back-button" class="options-item-wrapper clearfix">
                      <img class="svg options-item" src="https://cdn.playground-v2.programiz.com/assets/icons/back-arrow.svg" />
                    </div> -->
                    <div id="toggle-dark-mode-mobile" class="options-item-wrapper clearfix">
                        <img class="toggle-dark-mode-mobile-icon moon svg options-item" src="https://cdn.playground-v2.programiz.com/assets/icons/moon.svg" />
                        <img class="toggle-dark-mode-mobile-icon sun svg options-item" src="https://cdn.playground-v2.programiz.com/assets/icons/sun.svg" />
                    </div>
                    <button class="share-button-mob" title="Share">
                        <img class="svg share-icon" src="https://cdn.playground-v2.programiz.com/assets/icons/share.svg" />
                    </button>
                </div>
                <button class="upload-button tablet-share" type="button">
                    <input type="file" id="fileInput" accept=".txt">
                    <label for="fileInput">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 50 50" class="upload-icon svg replaced-svg">
                            <path d="M10.289 32.996a1 1 0 0 0-1 1v6.133a1 1 0 0 0 1 1h28a1 1 0 0 0 1-1v-6.133a1 1 0 1 0-2 0v5.133h-26v-5.133a1 1 0 0 0-1-1z"></path>
                            <path d="M24.333 34.996a1 1 0 0 0 1-1v-21.51l6.343 6.127a.996.996 0 0 0 1.413-.024 1 1 0 0 0-.024-1.414l-8.023-7.751-.002-.002-.013-.012c-.036-.035-.081-.05-.12-.078-.064-.046-.123-.097-.196-.127a.997.997 0 0 0-.357-.072c-.007 0-.014-.004-.021-.004s-.014.004-.021.004a1.001 1.001 0 0 0-.357.072c-.073.03-.132.081-.196.126-.039.029-.084.044-.12.079l-.012.011-.002.002-8.023 7.751a1 1 0 0 0 1.389 1.438l6.343-6.127v21.51a.998.998 0 0 0 .999 1.001z"></path>
                        </svg>
                    </label>
                </button>
                <div class="other-options-wrapper">
                    <!-- <div id="feedback-mobile" class="options-item-wrapper">
                      <a href="https://programiz.com/contact" class="options-item">
                        <img class="svg" src="https://cdn.playground-v2.programiz.com/assets/icons/message-square.svg" />
                      </a>
                    </div> -->

                    <div class="mobile-top-bar-run-button run">

                        <img src="https://cdn.playground-v2.programiz.com/assets/icons/play.svg" alt="run-icon" />
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("SideBar")


            <div class="editor-wrapper">
                <div class="editor-desktop-top-bar">
                    <div class="file-name">
                        main.py
                    </div>
                    <div class="desktop-top-bar__btn-wrapper">
                        <!-- Fullscreen toggle button -->
                        <button type="button" id="toggle-expanded-mode-desktop" title="Enter Fullscreen">
                            <img class="toggle-expanded-mode-mobile-icon expand svg" src="https://cdn.playground-v2.programiz.com/assets/icons/expand.svg" />
                            <img class="toggle-expanded-mode-mobile-icon minimize hidden svg" src="https://cdn.playground-v2.programiz.com/assets/icons/minimize.svg" />
                        </button>

                        <!-- Upload button -->
                        <button class="upload-button tablet-share" type="button">
                            <input type="file" id="fileInput" accept=".txt">
                            <label for="fileInput">
                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 50 50" class="upload-icon svg replaced-svg">
                                    <path d="M10.289 32.996a1 1 0 0 0-1 1v6.133a1 1 0 0 0 1 1h28a1 1 0 0 0 1-1v-6.133a1 1 0 1 0-2 0v5.133h-26v-5.133a1 1 0 0 0-1-1z"></path>
                                    <path d="M24.333 34.996a1 1 0 0 0 1-1v-21.51l6.343 6.127a.996.996 0 0 0 1.413-.024 1 1 0 0 0-.024-1.414l-8.023-7.751-.002-.002-.013-.012c-.036-.035-.081-.05-.12-.078-.064-.046-.123-.097-.196-.127a.997.997 0 0 0-.357-.072c-.007 0-.014-.004-.021-.004s-.014.004-.021.004a1.001 1.001 0 0 0-.357.072c-.073.03-.132.081-.196.126-.039.029-.084.044-.12.079l-.012.011-.002.002-8.023 7.751a1 1 0 0 0 1.389 1.438l6.343-6.127v21.51a.998.998 0 0 0 .999 1.001z"></path>
                                </svg>
                            </label>
                        </button>

                        <!-- Dark mode toggle button -->
                        <button type="button" id="toggle-dark-mode-desktop" title="Toggle dark mode">
                            <img class="toggle-dark-mode-mobile-icon moon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/moon.svg" />
                            <img class="toggle-dark-mode-mobile-icon sun svg" src="https://cdn.playground-v2.programiz.com/assets/icons/sun.svg" />
                        </button>

                        <!-- Share button -->
                        <button class="share-buttoncode" title="Share">
                            <img class="toggle-expanded-mode-mobile-icon svg share-icon" src="https://cdn.playground-v2.programiz.com/assets/icons/share.svg" />
                            Share
                        </button>

                        <!-- Run button -->
                        <button class="desktop-run-button run">
                            <span class="run-text">
                                &nbsp;Run&nbsp;
                            </span>
                        </button>
                    </div>
                </div>
                <button class="mobile-run-button run">
                    Run
                </button>
                <div id="editor">
@RenderBody()
                </div>
            </div>

            <div class="terminal-wrapper">
                <div class="terminal-desktop-top-bar">
                    <div class="shell-name">
                        Output
                    </div>
                    <div class="terminal-desktop-top-bar__btn-wrapper">
                        <button class="desktop-clear-button">
                            &nbsp;Clear&nbsp;
                        </button>
                    </div>
                </div>
                <div id="terminal"></div>
            </div>

        </div>
    </div>
    @await Component.InvokeAsync("Script")
</body>

</html>

WebCompiler/Views/Shared/_CompileHistory.cshtml
@model List<CompileHistory>

@foreach (CompileHistory cpHistory in Model)
{
    <div class="history-category history-box">
        <!-- First anchor tag on the left -->
        <a class="history-category-atag" asp-controller="CompileHistory" asp-action="showOldCompile" asp-route-compileId="@cpHistory.Id">
            <i class="bi bi-clock-history"></i>@cpHistory.Title 
        </a>

        <!-- Second anchor tag (close icon) on the right -->
        <a class="history-category-atag close-btnSideBar"  data-compileid="@cpHistory.Id">
            <i class="bi bi-x-circle close-icon"></i>
        </a>

    </div>

}

WebCompiler/Views/Shared/_Header.cshtml
<!--Header Start-->

<div class="header">
    <div class="header-wrapper">
        <div class="burger-menu">
            <button type="button" class="burger-menu-btn" title="Open navigation">
                <img class="svg burger-menu-btn-icon" src="https://cdn.playground-v2.programiz.com/assets/icons/burger.svg" />
            </button>
        </div>
        <div class="logo-wrapper">
            <h1 class="logo-title-wrapper">
                <a asp-controller="Home" asp-action="Index" class="logo-link">
                    <img id="logo" hidden />
                    <img id="logo" src="@Url.Content("~/assets/icons/logo.png")" />
                    <span class="logo-sub-title-wrapper">
                        <span class="logo-sub-title" id="compiler-title">
                            Online Compiler
                        </span>
                    </span>
                </a>
            </h1>
        </div>
    </div>
    <div class="compiler-header-ad">
        <div id="div-gpt-ad-Programizcom36786" class="content-top-ad">
        </div>

        <!-- buysell ads -->
        <div class="compiler-header-ad" id="carbon-block"></div>

    </div>
    <div id="add-replacement"></div>

    <div id="feedback-mobile">
        <a id="mobile-ad-link">&nbsp;Learn Python</a>
    </div>
</div>


<!--Header End-->

WebCompiler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    @* Compile History *@
    <title>Online C# Compiler</title>
    <link rel="shortcut icon" href="~/assets/icons/logo.png" />
    <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
    <link rel="stylesheet" type="text/css" href="/fonts/font.css">
    <link rel="stylesheet" type="text/css" href="~/assets/modalPopup/index.css">
    <link rel="stylesheet" type="text/css" href="~/assets/chatboxAI/index.css">
    <link rel="stylesheet" type="text/css" href="~/assets/sideBar/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/ace.js"></script>
    <script src="https://cmp.uniconsent.com/v2/stub.min.js"></script>
    <script async src='https://cmp.uniconsent.com/v2/a8d3ae4937/cmp.js'></script>
    <link rel="stylesheet" href="https://cdn.playground-v2.programiz.com/playground.css?v=1fsaf" />
    <link rel="stylesheet" type="text/css" href="/css/site.css" asp-append-version="true">

</head>

<body>
    <div class="container">
        <div class="spinner">
            <div class="loader"><span>{</span><span>}</span></div>
        </div>

        <!-- Share code -->
        <partial name="~/Views/Shared/_Share.cshtml" />

        <div class="wrapper">
            <!-- Header -->
            <partial name="_Header" />

            <!-- SideBar -->
            @{
                var hideSidebar = ViewData["HideSidebar"] as bool? ?? false;
            }

            @if (!hideSidebar)
            {
                @await Component.InvokeAsync("SideBar")
            }

            <!-- Render Body -->
            @RenderBody()

            <!-- Terminal -->
            @{
                var hideTerminal = ViewData["HideTerminal"] as bool? ?? false;
            }

            @if (!hideTerminal)
            {
                <partial name="_Terminal" />
            }

        </div>
    </div>
    <button class="toggle-chat-btn" onclick="toggleChatBox()">ChatBot</button>

    <div class="chat-box" id="chatBox">
        <div class="chat-header">
            Chat with AI
            <button class="close-btn" onclick="toggleChatBox()">X</button>
        </div>
        <div class="chat-content" id="chatContent">
            <!-- Chat messages will be appended here -->
        </div>
        <div class="chat-input">
            <textarea id="chatInput" placeholder="Type a message..." rows="1"></textarea>
            <button onclick="sendMessage()">Send</button>
            <button style="background-color:darkred" onclick="clearChat()">Clear</button>
        </div>
    </div>


    <script>
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelector('.spinner').style.display = 'none';
            document.querySelector('.wrapper').style.display = 'block';
        });
    </script>
    @* Compile History *@
    <!-- Other JavaScript files -->
    <script defer src="~/js/shareCode.js"></script>
    <script defer src="~/js/uploadFile.js"></script>
    <script defer src="~/js/download.js"></script>
    <script defer src="~/js/changeSideBar.js"></script>
    <script defer src="~/js/hideSpinner.js"></script>
    <script defer src="~/assets/modalPopup/index.js"></script>
    <script defer src="~/assets/sideBar/index.js"></script>
    <script defer src="~/assets/chatboxAI/index.js"></script>
    <script defer src="~/js/completeCodeHint.js"></script>
    <script defer src="~/js/typeName.js"></script>
    <script defer src="~/js/CompilerHandler.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.11/ext-language_tools.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/mousetrap/1.4.6/mousetrap.min.js"></script>
    <script defer src="https://cdn.playground-v2.programiz.com/build/final.js?v=resize-fixv3"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script defer src="~/js/compileHistory.js"></script>
</body>

</html>

WebCompiler/Views/Shared/_ModalPopup.cshtml
<button type="button" id="saveButton" class="upload-button tablet-share">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" class="save-icon">
        <path d="M17 3H7a2 2 0 00-2 2v14a2 2 0 002 2h10a2 2 0 002-2V5a2 2 0 00-2-2zm0 16H7V5h10v14zM8 7h8v2H8V7zm2 6h4v2h-4v-2z" />
    </svg>
</button>

<!-- Modal -->
<div class="custom-modal-overlay" id="customModal">
    <div class="custom-modal-content">
        <div class="custom-modal-header">
            <h5 class="custom-modal-title">Save Compile History</h5>
            <button type="button" class="custom-close-btn" id="closeCustomModal">&times;</button>
        </div>
        <div class="custom-modal-body">
            <label for="titleInput" class="title-label">Title</label>
            <input type="text" id="titleInput" class="title-input" />
        </div>
        <div class="custom-modal-footer">
            <button type="button" class="custom-modal-close-btn" id="closeCustomModalFooter">Close</button>
            <button type="button" class="custom-modal-save-btn">Save history</button>
        </div>
    </div>
</div>

WebCompiler/Views/Shared/_Share.cshtml
<!--Share-->

<div class="share-link-generating-modal" style="display: none;">
    <div class="modal-backdrop-share"></div>
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Generating Link</h2>
            <h2 class="modal-title modal-title-mob">Generating Link</h2>
            <button type="button" class="close-modal" title="Close" onclick="window.closeModal()">X</button>
        </div>
        <div class="modal-body">
            <div class="progress-bar">
                <div class="progress"></div>
            </div>
        </div>
    </div>
</div>

<!--End-->

WebCompiler/Views/Shared/_SideBar.cshtml
<!--SideBar Start-->

<div class="sidebar-wrapper">
    <a href="https://localhost:7028/python" class="change-lang-btn python" title="Online Python Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/python.svg" alt="Python Online" />
    </a>
    <a href="https://localhost:7028/csharp" class="change-lang-btn csharp" title="Online C# Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/csharp.svg" alt="C# Online" />
    </a>
    <a href="https://localhost:7028/r" class="change-lang-btn r " title="Online R Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/r.svg" alt="R Programming Online" />
    </a>
    <a href="https://localhost:7028/sql" class="change-lang-btn sql" title="Online SQL Editor">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/sql.svg" alt="SQL Online" />
    </a>
    <a href="https://localhost:7028/html" class="change-lang-btn html" title="Online HTML/CSS Editor">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/html.svg" alt="HTML/CSS Online" />
    </a>
    <a href="https://localhost:7028/java" class="change-lang-btn java " title="Online Java Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/java.svg" alt="Java Online" />
    </a>
    <a href="https://localhost:7028/c" class="change-lang-btn c " title="Online C Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/c.svg" alt="C Programming Online" />
    </a>
    <a href="https://localhost:7028/c++" class="change-lang-btn cpp " title="Online C++ Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/cpp.svg" alt="C++ Programming Online" />
    </a>
    <a href="https://localhost:7028/javascript" class="change-lang-btn javascript " title="Online JavaScript Compiler (Editor)">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/javascript.svg" alt="JavaScript Online" />
    </a>
    <a href="https://localhost:7028/golang" class="change-lang-btn golang " title="Online Golang Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/golang.svg" alt="Golang Online" />
    </a>
    <a href="https://localhost:7028/php" class="change-lang-btn php " title="Online PHP Compiler ">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/php.svg" alt="PHP Online" />
    </a>
    <a href="https://localhost:7028/swift" class="change-lang-btn swift " title="Online Swift Compiler ">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/swift.svg" alt="Swift Online" />
    </a>
    <a href="https://localhost:7028/rust" class="change-lang-btn rust " title="Online Rust Compiler">
        <img class="change-lang-btn-icon svg" src="https://cdn.playground-v2.programiz.com/assets/icons/rust.svg" alt="Rust Online" />
    </a>

</div>

<!--SideBar End-->

WebCompiler/Views/Shared/_Terminal.cshtml
<!--Terminal Start-->

<div class="terminal-wrapper" style="width:35%">
    <div class="terminal-desktop-top-bar">
        <div class="shell-name">
            Output
        </div>
        <div class="terminal-desktop-top-bar__btn-wrapper">
            <button class="desktop-clear-button">
                &nbsp;Clear&nbsp;
            </button>
        </div>
    </div>
    <div id="terminal"></div>
</div>

<!--Terminal End-->